[project]
name = "kstar-tokamak-simulator-streamlit"
version = "2.0.0-beta.2"
requires-python = ">=3.11,<3.12"
description = "A tokamak (nuclear fusion reactor) simulator with LSTM-based neural network (KSTAR-NN)"
authors = [{ name = "Jaemin Seo", email = "jseo@cau.ac.kr" }]
maintainers = [{ name = "Myeongseop Jeon", email = "jeonms9338@snu.ac.kr" }]
license = "MIT"
readme = "README.md"
dependencies = [
  "tensorflow-cpu~=2.15",
  "keras~=2.15",
  # "QtPy==2.4.1",
  "numpy~=1.26",
  "scipy~=1.12",
  # "matplotlib==3.8.2",
  "streamlit~=1.30",
  "plotly~=5.18",
  "pandas~=2.2",
  "pillow~=10.2",
  # "numba==0.58.1",
]

[dependency-groups]
dev = ["ruff==0.11.13"]

[tool.uv]
package = false

[tool.ruff]
include = ["./kstar_simulator.py", "common/*.py"]

[tool.ruff.lint]
select = ["I", "E4", "E7", "E9", "F"]

[tool.ruff.format]
exclude = ["common/**"]
